SUSE/saphanabootstrap-formula

README.md
Just a minor change of README, remove the duplicate "zypper addrepo"
=> Remove duplicate zypper in README.

saphanabootstrap-formula.changes, saphanabootstrap-formula.spec
Version bump 0.1.1
* Include the salt-formulas-configuration dependency on
SLE/Leap 15-SP1 and higher. This package configures the shared salt
formulas location (/usr/share/salt-formulas) to be used by SUMA 4.0
or salt in standalone mode.
* Drops the saphanabootstrap-formula-suma package, as the forms metadata
will be available only on SUMA 4.0 using the shared location.
=> Install the Salt files on the salt-shared location from 15-SP1.

hana/packages.sls, saphanabootstrap-formula.spec
Besides the `license` macro, an issue with the python-shaptools package name has been fixed (to install the package correctly in python-shaptools and python2-shaptools cases)
=> Add condition to license macro

hana/enable_cost_optimized.sls, templates/srTakeover_hook.j2
Contains the fixes for the sr hook to undo changes cost-optimized related parameters on secondary HANA node after takeover
- Make the hdbcli client py files extraction compatible with new HANA revisions, as tarball has different structure in older HANA revisions
- Added the [ha_dr_provider_srTakeover] section to global.ini file 
- Other minor fixes to naming
- Added improvements suggested from other PR https://github.com/SUSE/saphanabootstrap-formula/pull/38
Tested in local environment
=> Fix/sr hook for cost-optimized

hana/packages.sls, saphanabootstrap-formula.changes
In order to fix the errors caused during `pkg.info_available`, the `refresh` option is disabled. 
I have tested several times and I have not found the previous issue again.
PD:
This PR comes from the need to fix:
https://github.com/SUSE/saphanabootstrap-formula/pull/52
=> Updata pkg.info_available call to avoid errors

saphanabootstrap-formula.changes, saphanabootstrap-formula.spec, templates/scale_up_resources.j2
Azure changed the Load-Balancer listener to socat as netcat does not allow more than one concurrent connection. For that, we need to install the package socat :
https://github.com/SUSE/habootstrap-formula/pull/33
and correspondingly, our template for HANA (and Netweaver in the future) needs to be adapted to use the updated command, instead of the old nc command.
```
crm configure primitive rsc_nc_HN1_HDB03 anything \
params binfile="/usr/bin/socat" cmdline_options="-U TCP-LISTEN:62503,backlog=10,fork,reuseaddr /dev/null" \
op monitor timeout=20s interval=10 depth=0
```
Reference:
https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability#create-sap-hana-cluster-resources
=> Change Cluster Configuration Template to use `socat` inplace of `netcat` for Azure

hana/enable_secondary.sls, pillar.example, saphanabootstrap-formula.changes
The formula has an issue. If the primary node is not defined the secondary cannot be provisioned as it depends in the primary node password. This fixes this issue adding new options to get the primary password.
The options:
The primary password is retrieved in this order
1. If the primary node is defined in the pillar, primary password will be used
2. If secondary.primary_pass is defined this password will be used
3. The secondary machine password will be used
=> Add new options to get primary node password

saphanabootstrap-formula.changes, saphanabootstrap-formula.spec, templates/scale_up_resources.j2
Use the new `cloud_provider` parameter. As the template is used in habootstrap-formula `grains['cloud_provider']` will always exist.
Depends on: 
https://github.com/SUSE/habootstrap-formula/pull/38
https://github.com/SUSE/habootstrap-formula/pull/38/files#diff-ede8388134830516402a39e126add733R6
=> Use correct pillar entry to know cloud provider

hana/install.sls, pillar.example, saphanabootstrap-formula.changes, saphanabootstrap-formula.spec
Add the option to pass xml file containing passwords for installing hana.
system_user_password/sapadm_password in pillar will used if XML file is not provided
Related PR:
https://github.com/SUSE/shaptools/pull/48
https://github.com/SUSE/salt-shaptools/pull/46
=> Pass xml file to install hana if this file is provided

README.md
From https://www.suse.com/brandcentral/suse/identity.php
"SUSE Corporate NAME
SUSE should always be spelled with all caps. Never lowercase the U (SuSE) or the entire name (suse)."
=> README: follow branding guidelines for "SUSE"

hana/defaults.yaml, hana/extract_hdbserver.sls, hana/init.sls, hana/install.sls, hana/install_pydbapi.sls, pillar.example, saphanabootstrap-formula.changes, saphanabootstrap-formula.spec
Adding the sapcar extraction functionality to extract HANA database sar file.
With this PR, I allow did following changes to how HANA installation works.
- Set a Default extraction directory for hana: `/sapmedia/HANA`
- Added a global `software_path` variable, The precedence for hana install media now looks like this: `local node entry for software_path` > `global software_path` > `hdbserver_extract_dir`
I have added in pillar notes that `hdbserver_extract_dir` will be used if both `software_path` are not provided
- Copy the `SIGNATURE.SMF` to  directory containing `hdblcm` executable (ie `SAP_HANA_DATABASE`)
=> Feature/sapcar support 

saphanabootstrap-formula.changes, saphanabootstrap-formula.spec, templates/scale_up_resources.j2
Updating the colocation weight in cluster template for Azure
as `g_ip_{{ sid }}_HDB{{ instance }}` was not moving together with current SAP master
Fixes:https://github.com/SUSE/saphanabootstrap-formula/issues/85 and tested with azure deployment.
Reference:
-https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability
-https://github.com/MicrosoftDocs/azure-docs/commit/f6bead3aae6e5b067ee113597a0cc57cdbaf46f2
=> Update colocation weight for col_saphana_ip for Azure provider

.travis.yml
Updating the source configuration for salt gpg key in travis build configuration.
It seems that the saltstack repo removed the Ubuntu `14.04` distrution, and we are getting build error in our formulas due to using the old url.
=> Update the saltstack repo url for build validation

pillar.example, saphanabootstrap-formula.changes, templates/scale_up_resources.j2
Add the HANA active/active setup cluster resources to the template. To use the active/active setup:
- The `operation_mode` must be `logreplay_readaccess` in the hana.sls file
- The entry `virtual_ip_secondary` must be added to the `cluster.sls` file (and `route_name_secondary` for GCP case) (this belongs to `habootstrap-formula` anyway`) Something like:
```
template:
source: /usr/share/salt-formulas/states/hana/templates/scale_up_resources.j2
parameters:
...
virtual_ip_secondary: 192.168.1.15
route_name_secondary: gcp_route_name # only for GCP
...
```
Docs about Active/Active setup:
https://documentation.suse.com/sbp/all/html/SLES4SAP-hana-sr-guide-PerfOpt-12/index.html#_activeactive_read_enabled_scenario
https://help.sap.com/viewer/4e9b18c116aa42fc84c7dbfd02111aba/2.0.04/en-US/8231617177f …
=> Add HANA active/active resources to the template

README.md, saphanabootstrap-formula.spec
Changing the location of `pillar.example` file in package,
and fix typo in readme
=> Fix pillar.example file location in package

_service, hana/monitoring.sls, saphanabootstrap-formula.changes, templates/hanadb_exporter.j2
this pr change to use `/usr/etc` by default for configuration files.
I do think this is safe enough for all systems. All linux systems have that folder allthough isn't used.
https://github.com/SUSE/hanadb_exporter/pull/78
works
=> Use /usr/etc by default

hana/defaults.yaml, pillar.example, saphanabootstrap-formula.changes
To avoid conflict with ready-only sap media mount points, we need to update the location where SAP HANA archives are extracted. Currently, both the default mounting point for sap media, and extraction path for sap media are same: `/sapmedia/HANA`
This can cause issues as mentioned by Peter Schinagl in
https://github.com/SUSE/ha-sap-terraform-deployments/pull/546
1) Could you suggest if there is a better naming for this extraction directory?
2) Based on my research, there is no restriction on where this location can be, except it has to have right permission. 
However, I think placing it under the `/hana` sub directories may not be a good idea. Considering that `/hana/data` `/hana/log`
may run out of disk space, and `/hana/shared/` being used as shared mount directory amongst the hana …
=> Change sap hana media extraction location 

form.yml, hana/install.sls, hana/pre_validation.sls, saphanabootstrap-formula.changes
1) Update suma form with new entries mainly related to:
- saptune
- ha cluster states
- hana media extraction logic
- hdb password xml file
- monitoring
- fix for hana installation media preference in the form (this matches the actual usage in pillar )
2) Update how the `hana_extract_dir`  is  imported/used in hana media extraction states
3) Update pre validation logic
This PR replaces https://github.com/SUSE/saphanabootstrap-formula/pull/90
Tested with Suse manager `4.1`  web interface and highstates
=> update Suse manager form and fix hana_extract_dir variable usage

metadata.yml, saphanabootstrap-formula.changes
With this change, both SAP HANA and NW formulas will show under the SAP deployment group, under the SUMA formulas list
=> Update the SUMA metadata to show hana form under SAP deployment group

hana/enable_cost_optimized.sls, hana/extract_hana_package.sls, hana/install.sls, hana/macros/get_hana_exe_extract_dir.sls, hana/monitoring.sls, saphanabootstrap-formula.changes, saphanabootstrap-formula.spec
The underlying problem:
Using the `unrar`/ `unar` packages to extract multipart rar archives... did not support/work for extraction with top-level directory skipping.
Saltstack rar extraction functions did not work as well.
For example: `51053381_part1.exe`  `51053381_part2.rar` .. multipart archives will extract to a directory named `51053381` under location we specify, and not directly to specified output directory.
This becomes problem when we want to tell the installer where hana media is located.
The hana installer needs to know this folder name (as part of complete software path) which contains the `LABEL.asc` file.
Workaround:
I did the jinja workaround logic to find /calculate the folder name, from the name of archive itself, and append it to path, which was working fine, until …
=> Workaround for installation when using exe archive

saphanabootstrap-formula.changes, templates/scale_up_resources.j2
Enable native fencing optionally.
At some cases, `sbd` is used as fencing mechanism, and for those cases, we need to disable the native fencing mechanism.
By now, we only have it for `gcp` and `aws` (for `azure` will be the same).
FYI: @peteratsuse
=> Use native fencing optionally

_service, hana/defaults.yaml, hana/enable_cost_optimized.sls, hana/extract_hana_package.sls, hana/macros/get_hana_client_path.sls, hana/monitoring.sls, pillar.example, saphanabootstrap-formula.changes
With respect to: https://github.com/SUSE/ha-sap-terraform-deployments/issues/558
I have added the option to install HANA Client packages from SAR file for monitoring, cost-optimized HANA.  This is needed if the HANA database is installed using a SAR file where the client is not present.
This option works when you are using HANA DB archive SAR file only. In other cases, HANA platform folder or package will already have the HANA client.
There are 3 options now to use HANA Client. Below is their preference order:
1) HANA platform folder/archives (except hana db sar archive)- HANA client already included with this. So no additional parameters required for this option
2) Extracted hana client folder provided via variable: `hana_client_software_path` 
3) HANA Client sar file provided via …
=> HANA client SAR archive extraction

hana/enable_primary.sls, hana/enable_secondary.sls, hana/ha_cluster.sls, hana/monitoring.sls, saphanabootstrap-formula.changes
If the HANA installation fails, the subsequent states do not have to be executed. Right now, I have added the `require` statement to states following the HANA installation, and this will stop further salt states from execution
The overall runtime of salt execution after the failure, is now reduced. I have tested with deployments.
Note that some states like monitoring(grafana, loki) etc are executed from terraform project, and still get executed.
=> Abort formula execution if the SAP HANA installation fails

hana/saptune.sls, saphanabootstrap-formula.changes
Currently, the deployment doesn't start the saptune daemon. It is needed to get the sap tuning back especially after system reboot.
I have added the `saptune daemon start` cmd. which will be available in saptune version 3, but internally mapped to the new command `saptune service start`
Resolves the `ERROR: The parameters listed above have deviated from SAP/SUSE recommendations.`
=> Start the saptune systemd service after saptune solution is applied

hana/enable_cost_optimized.sls, hana/extract_hana_package.sls, hana/macros/get_hana_client_path.sls, hana/monitoring.sls, pillar.example, saphanabootstrap-formula.changes
In some scenarios the hana client is not found properly. 
- HANA client and server SAR archives are already extracted in the sapmedia folder
- HANA database SAR is extracted and HANA client is in SAR format
To fix that I have done some preference changes. Now, if the `hana_client_archive_file` or `hana_client_software_path
` are present they will have preference over the database/platform options.
The change includes:
1. The HANA client is always extracted if the data is present. Before it was extracted only if the database was a SAR option
2. `hana_client_archive_file` or `hana_client_software_path
` have preference over other options
I have tested the next scenarios and everything worked fine:
Database as SAR - Client as SAR -> OK
Database as SAR - Client already extracted -> OK …
=> Fix hana client preference usage to use first the defined client method

hana/ha_cluster.sls, saphanabootstrap-formula.changes
Related to: https://github.com/SUSE/shaptools/pull/65
Fix some sidadm conversions. If the provided sid is in uppercase the created states are incorrect, specifically the ones managing the `sudoers` entry content.
The rest of the uses of the sidadm are safe as they are treated in lower layers (`shaptools` specifically)
Some info: https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-CostOpt-12/#_allowing_sidadm_to_access_the_cluster
FYI: @petersatsuse
=> Fix how sidadm user is transformed to lowercase in ha cluster states

saphanabootstrap-formula.changes, templates/scale_up_resources.j2
The azure-lb resource receives an stickiness=0 to not influence on
transitions calculations as the HANA resources have more priority.
Ref: https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/sap-hana-high-availability#create-sap-hana-cluster-resources
=> Set correct stickiness for the azure-lb resource

form.yml, hana/monitoring.sls, pillar.example, saphanabootstrap-formula.changes, templates/hanadb_exporter.j2
Simple change to reduce the hanadb_exporter start timeout to 30 seconds
(And it took advantage of fixing one of the states involved in the exporter initialization)
=> Change hanadb_exporter start timeout value to 30s

hana/monitoring.sls, saphanabootstrap-formula.changes, templates/scale_up_resources.j2
prometheus-hanadb_exporter cluster primitiv adoption, the fix will address this issue:
https://github.com/SUSE/ha-sap-terraform-deployments/issues/686
The change is needed to avoid a HANA DB takeover just in case that the local hanadb_exporter has an issue and is not able to start.
=> prometheus-hanadb_exporter cluster primitiv adoption fix SUSE/ha-sap-terraform-deployments/#/686

templates/scale_up_resources.j2
This is a follow up for #130 which uses pillars set in `habootstrap-formula` instead of grains.
This adds the needed resources to implement native fencing on azure.
It also defines for all cloud providers the same defaults to use native fencing as https://github.com/SUSE/ha-sap-terraform-deployments/.
```
grep -A5 hana_cluster_fencing_mechanism */variables.tf | grep 'variable |default'
1:openstack/variables.tf:variable "hana_cluster_fencing_mechanism" {
4:openstack/variables.tf-  default     = "sbd"
8:libvirt/variables.tf:variable "hana_cluster_fencing_mechanism" {
11:libvirt/variables.tf-  default     = "sbd"
21:gcp/variables.tf:variable "hana_cluster_fencing_mechanism" {
24:gcp/variables.tf-  default     = "native"
34:azure/variables.tf:variable "hana_cluster_fencing_mechanism" { …
```
=> add native fencing for microsoft-azure - follow up

_service, hana/ha_cluster.sls, saphanabootstrap-formula.changes
Starting with version 0.180 the SAPHanaSR-ScaleOut package supports SAP HANA scale-out multi-target system replication. That means you can connect a third HANA site by system replication to either of the two HANA sites which are managed by the SUSE HA cluster.
More Details can be found here:
https://www.suse.com/c/sap-hana-scale-out-upgrade-details/
https://www.suse.com/c/sap-hana-scale-out-multi-target-upgrade/
To enable this feature, a different hook script needs to be used:
~~/usr/share/SAPHanaSR-ScaleOut/SAPHanaSR.py~~
/usr/share/SAPHanaSR-ScaleOut/SAPHanaSrMultiTarget.py
This PR enables the new Hook if it is available and also migrates old setups (hook and sudoers).
fixes https://github.com/SUSE/saphanabootstrap-formula/issues/135 
fixes …
=> use multi-target Hook on HANA scale-out and use sudoers.d file

_service, hana/ha_cluster.sls, saphanabootstrap-formula.changes, templates/cluster_resources.j2
-  25b031d60d9a76b68c568e5a5585c4a18af25985 fixes the updated SAPHanaSR hook code introduced in #136 to not remove the hook again.
- 543ed4fd3ed3584047ee42d1763e02d4e70ea924 adds `None` as a condition not to deploy majority maker constraints. This will be the case if the pillar/grain is not set or empty.
=> fixes for SAPHanaSR hook and Majority Maker

_service, hana/ha_cluster.sls, saphanabootstrap-formula.changes, templates/ha_cluster_sudoers.j2
This PR tackles https://bugzilla.suse.com/show_bug.cgi?id=1196642 which suggests:
- to get rid of the temporary unsecure sudoers file in `/tmp/` 
- do not use `*` in suders rules
The outcome of a discussion with the owners of https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-scaleOut-PerfOpt-15/index.html was, that it is OK to go this way (getting rid of `*`). The best practices have to be seen as a general guideline and might or might not suggest security best practices.
In addition to the changes named above, it introduces a template file for the SAPHanaSR sudoers. This way the templating is done in the template instead of the state and we can pass a [salt slot](https://docs.saltproject.io/en/latest/topics/slots/index.html) to evaluate the "srHookGen" at a very late stage …
=> make sudoers rules more secure

_service, hana/ha_cluster.sls, saphanabootstrap-formula.changes, templates/ha_cluster_sudoers.j2
This adds the "SAPHanaSR takeover blocker" feature described in https://www.suse.com/c/sap-hana-cockpit-with-suse-ha-integration-greatly-improves-data-integrity/
It is available for SAP HANA Scale Up deployments.
- adds new `susTkOver.py` hook to `global.ini` if script is found
- add new sudo rule for `SAPHanaSR-hookHelper` which is called by `susTkOver.py` (always added)
Fixes #143
=> add SAPHanaSR takeover blocker

_service, saphanabootstrap-formula.changes, saphanabootstrap-formula.spec
A previous change to the spec file prevented the build of RPMs for SLES.  This change has been reverted.
=> revert spec file changes

.github/workflows/formulaCI.yml
The branch 'master' was renamed 'main' earlier in the year.  When this change was made, the github workflow was not updated.  This change updates the workflow to reflect the branch name change and ensures that new releases automatically submitted to OBS.
=> fixed CI following branch name change
